# Generated by Django 4.2.1 on 2023-05-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_api', '0003_alter_rating_num_ratings_alter_rating_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='total_rating',
            field=models.FloatField(default=1),
        ),
    ]
