# Generated by Django 4.2.1 on 2023-05-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_api', '0004_alter_rating_total_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='total_rating',
            field=models.FloatField(default=0),
        ),
    ]
